language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - '[[ "$TRAVIS_PHP_VERSION" == "5.5" ]] || composer install -n'
  - '[[ "$TRAVIS_PHP_VERSION" != "5.5" ]] || composer update -n --prefer-lowest'
  - "mysql -e 'create database zf2_test;'"
  - ./vendor/bin/doctrine-module orm:schema-tool:create

  - ./vendor/bin/codecept build

script:
  - '[[ "$TRAVIS_PHP_VERSION" > "5.5" ]] || ./vendor/bin/codecept run functional,doctrine -v'
  - '[[ "$TRAVIS_PHP_VERSION" < "5.6" ]] || ./vendor/bin/codecept run functional -v'
